### ISSUE TITLE
janalyse.fr is down

### ISSUE THREAD

**Issue by peterrosell** [dacr/jassh#37]
It seems like the server janalyse.fr is down so the package can't be fetched by sbt.
Does a mirror site exist?

**Comment by scalaster** [comment]
+1 for this issue. I have got dependent projects I am no longer able to build because janalyse.fr is down. mavencentral and others have got more recent versions but my projects depend on an older version 0.6.3. I tried build from source from rel_0.6.4 branch but was unable to build from source because it again needs janalyse.fr to resolve some dependencies. Any info when janalyse.fr repo or a mirror will become available?

**Comment by dacr** [comment]
If you still need it, I can publish old releases on maven central.

**Comment by peterrosell** [comment]
We have updated to newer version so no problem for me.
